language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args:
        - '--as-cran --use-valgrind'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      dist: precise
      compiler: clang

    - os: linux
      dist: trusty
      r: devel
      compiler: clang
      sudo: required
      addons:
        apt:
          packages:
            - r-cran-rjava

    - os: osx
      r: release
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
notifications:
  email:
    on_success: change
    on_failure: change
